apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- range $file, $content := .Values.config }}
  {{ $file }}: |
    {{ tpl $content $ | nindent 4 }}
  {{- end }}