apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-svc
  {{- if .Values.monitoring.enabled }}
  annotations:
    {{- range $key, $value := .Values.monitoring.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}

