apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required "Can't escape name:" .Values.name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.drink | upper | quote }}
  food: {{ .Values.food | title | quote }}
