apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "O-my-function" .Values.name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.drink | upper | quote }}
  food: {{ .Values.food | title | quote }}
