apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: alice-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
  {{- range .Values.users }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . }}
  {{- end }}
